[project]
name = "neinhorn"
version = "0.1.0"
description = "Tools for generating mixtape cards and managing MP3s"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "qrcode",
    "Pillow",
]

[project.scripts]
gen-card = "neinhorn.gen_card:main"
number-mp3s = "neinhorn.number:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
