[project]
name = "zauberbox"
version = "0.1.0"
description = "Tools for generating mixtape cards and managing MP3s"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "qrcode",
    "Pillow",
    "flask",
    "minify-html",
]

[project.scripts]
gen-card = "zauberbox.gen_card:main"
number-mp3s = "zauberbox.number:main"
combine-cards = "zauberbox.combine:main"
mock-server = "zauberbox.web.mock_server:main"
build-web = "zauberbox.web.build_web:main"
build-ui-sounds = "zauberbox.build_ui_sounds:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
