[env:waveshare_s3_audio]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = esp32-s3-devkitc1-n16r8
framework = arduino, espidf

; Hardware Specifications: 16MB Flash, 8MB Octal PSRAM (OPI)
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_build.maximum_size = 16777216
board_build.partitions = boards/dev-16MB.csv

build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -D CONFIG_ESP_HOSTED_IDF_SLAVE_TARGET='"esp32c6"'
    -D configTASKLIST_INCLUDE_COREID=1       ; Include CoreID in TaskList
    -D CORE_DEBUG_LEVEL=3                    ; 0 None, 1 Error, 2 Warn, 3 Info, 4 Debug, 5 Verbose
    -D CONFIG_ARDUHAL_LOG_COLORS=1
    -D ARDUINO_RUNNING_CORE=1                ; Arduino Runs On Core (setup, loop)
    -D ARDUINO_EVENT_RUNNING_CORE=1          ; Events Run On Core
    -D AUDIOTASK_CORE=0                      ; 0 or 1 - reads from the InBuffer, decodes and feeds I2S
    -D BOARD_HAS_PSRAM=1
    -D MONITOR_SPEED=${this.monitor_speed}
    -Wall
    -Wextra
    -Wno-cpp                                 ; Disable #warning directive warnings
    -Wno-format                              ; Disable all format string warnings
    -Wno-unused-function
    -Wno-missing-field-initializers
    -fdiagnostics-color=always
    -Wno-error=class-memaccess
    -std=gnu++20

build_unflags = -std=gnu++11

monitor_speed = 115200
monitor_filters = esp32_exception_decoder, send_on_enter
upload_speed    = 921600  ; 921600, 512000, 460800, 256000, 115200

platform_packages =
  toolchain-xtensa-esp32s3@12.2.0+20230208

lib_deps =
    https://github.com/schreibfaul1/ESP32-audioI2S.git @ ^3.4.5
    ayresnet/AyresWiFiManager @ ^2.0.1
    adafruit/Adafruit NeoPixel @ ^1.12.0

custom_component_remove =
                          espressif/network_provisioning
                          espressif/esp-zboss-lib
                          espressif/esp-zigbee-lib
                          espressif/esp_rainmaker
                          espressif/rmaker_common
                          espressif/esp_insights
                          espressif/esp_diag_data_store
                          espressif/esp_diagnostics
                          espressif/cbor
                          espressif/qrcode
                          espressif/esp-sr
                          espressif/libsodium
                          espressif/esp-modbus
                          chmorgan/esp-libhelix-mp3
                          espressif/esp32-camera

