[env:waveshare_s3_audio]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Hardware Specifications: 16MB Flash, 8MB Octal PSRAM (OPI)
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_build.maximum_size = 16777216
board_build.partitions = default_16MB.csv

build_flags = 
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

monitor_speed = 115200

lib_deps =
    # Example audio library highly compatible with this board
    # https://github.com/schreibfaul1/ESP32-audioI2S
    https://github.com/schreibfaul1/ESP32-audioI2S.git
